### ISSUE TITLE
when building: cannot open file 'WzLib.lib'

### ISSUE THREAD

**Issue by joshhmann** [HeavenClient/HeavenClient#100]
was having this issue when building the project. I tried looking for references to WzLib.lib but could not find anything 

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'WzLib.lib'	MapleStory	C:\Users\Josh\Documents\GitHub\HeavenClient\LINK	1

**Comment by glepetic** [comment]
check issue #96

**Comment by joshhmann** [comment]
ah found it, was in property page / linker / input / addtional dependencies
