### ISSUE TITLE
Black screen after start game

### ISSUE THREAD

**Issue by ivandgetic** [HeavenClient/HeavenClient#101]
Use VS2022 Compile this project and remove wzLib.lib link
all *.nx files use NoLifeWzToNx Convert from lastest client .wz files
When I start game, It just show my cursor postion in console, nothing show in game and no sound

**Comment by ryantpayton** [comment]
Did you test this with the latest version I just pushed on Dec 3?
https://github.com/HeavenClient/HeavenClient/commit/a6ec68b3f8d546368f742dc1b0fec2f7727b09b1

As for the music mine is also doing that. I'm going to fix this soon.
All make sure your wz files match the version included in the build or close enough.
https://github.com/HeavenClient/HeavenClient/blob/master/Configuration.h#L232

I tested with v228.3

**Comment by ivandgetic** [comment]
yes,I has been updated to the latest code on Dec 3.
and maplestory client version is v228.4,I think the wz files will no big difference.
but some different is I use NoLifeWzToNx.exe without -c arg,
because I add -c, It cause many problems

**Comment by ryantpayton** [comment]
This is the script I use:
x64\Debug\NoLifeWzToNx x64\Debug\files -c
pause

It has to have -c flag. I converted all files from v228.3 without any issues.
What issues are you experiencing.
Also make sure you are using the latest code from NoLifeWzToNx as I have made updates in there as well.
Latest is May 9:
https://github.com/ryantpayton/NoLifeWzToNx/commit/237e29f932c61294ff9d60a3f071217a2e784590

**Comment by ivandgetic** [comment]
![error](https://user-images.githubusercontent.com/3357248/145049199-3a6a7500-3428-4f12-8a9e-66916634c545.png)

Character.wz
Effect.wz
Map.wz
Mob002.wz

The above files will report errors
Finally I ignore the problem and enter game.

**Comment by ryantpayton** [comment]
@ivandgetic I just pushed an update to NoLifeWzNz. Can you get the latest and try again?
You might have to rebuild it.

**Comment by ivandgetic** [comment]
I have tried the latest version of NoLifeWzNz and no error.
But client also have bug.
When I created a character ,the std::vector<CharLook> charlooks size =0 
I guess the nx resource may not be loaded properly
https://github.com/HeavenClient/HeavenClient/blob/master/IO/UITypes/UICharSelect.cpp#L877

**Comment by Bear2leaf** [comment]
> I have tried the latest version of NoLifeWzNz and no error.
> But client also have bug.
> When I created a character ,the std::vector charlooks size =0
> I guess the nx resource may not be loaded properly
> https://github.com/HeavenClient/HeavenClient/blob/master/IO/UITypes/UICharSelect.cpp#L877

I used to have the same problem, you should try use this new server https://github.com/ryantpayton/MapleStory.git instead of heavenMS, copy heavenMS's wz directory into MapleStory's root directory, then it may work fine. Maybe this should be mentioned in README.

by the way, if you encounter problem with pic, turn off server's enable_pic and try again.
and open skill panel will cause client crash, don't know why, doesn't happen before.

<img width="752" alt="image" src="https://user-images.githubusercontent.com/20519536/145215431-596570d8-fd28-4b2d-b569-22d4a7d41dea.png">

**Comment by ivandgetic** [comment]
Thank you for your help, Finally i got it

**Comment by Bear2leaf** [comment]
邮件已收到——陈凯杰

**Comment by ryantpayton** [comment]
Nice guys! @Bear2leaf yeah I'll get to updating that link. Good idea.
I'll close this issue out to. Let me know if you guys have any more issues.

**Comment by HoneyTorres** [comment]
> 

可以把你转化前的wz文件给我么？

**Comment by HoneyTorres** [comment]
> I have tried the latest version of NoLifeWzNz and no error. But client also have bug. When I created a character ,the std::vector charlooks size =0 I guess the nx resource may not be loaded properly https://github.com/HeavenClient/HeavenClient/blob/master/IO/UITypes/UICharSelect.cpp#L877

可以把你转化前的wz发我一份么？
