### ISSUE TITLE
which UI.nx versions are you using ?

### ISSUE THREAD

**Issue by leeqiufeng** [HeavenClient/HeavenClient#102]
which UI.nx versions are you using ?

**Comment by leeqiufeng** [comment]
which client(wz) version are you using ?

**Comment by Bear2leaf** [comment]
according to "Required Files" section in readme, you can find client wz version in Configuration.h, which is 228.3

**Comment by leeqiufeng** [comment]
tks~

**Comment by fmnijk** [comment]
How to change it to another version?

**Comment by ryantpayton** [comment]
> How to change it to another version?

Why do you want to change it? What version do you want?

**Comment by fmnijk** [comment]
I want to change it to TMS v122. It's the last version before BB in TMS.

**Comment by ryantpayton** [comment]
> I want to change it to TMS v122. It's the last version before BB in TMS.

You have to write everything to work with that specific version. It's not plug n play. As versions change, the mappings to the images get rearranged and they add/delete stuff.

Without work on your end you'll never have it. Convert the TMS files to NX and run the client in debug and fix the missing links.

**Comment by fmnijk** [comment]
This project is using GMS v228.3 right? I would like to know how to go back to GMS v83.

**Comment by fmnijk** [comment]
Dose the server side you used support the events and BOSS quests in GMS v228.3?
