### ISSUE TITLE
Is there any repository for nx/wz files?

### ISSUE THREAD

**Issue by tlz4320** [HeavenClient/HeavenClient#103]
I used wz files from google drive including current_wz 397 203 but all of that commit UI version error.
And version 228.3 in configuration.h is needed, but now I can't find it from internet.
Because of I live in China, it is difficult for me to download GMS with 20GM. 
Therefore, is there any repository for 228.3 wz files?

**Comment by tlz4320** [comment]
I finally got newest version of UI.wz But can't convert to nx.

**Comment by ryantpayton** [comment]
I'm not going to spoon-feed. Please read all documentation.

**Comment by tlz4320** [comment]
In documentation, NO 228.3 WZ file download link. AND I HAVE TRIED IN RaGEZONE, there is no 228.3 archive. And in your UI design, low version map and low version UI.wz can't be used for fixed subnode you use.
