### ISSUE TITLE
MS Version? 

### ISSUE THREAD

**Issue by EasyDrax** [HeavenClient/HeavenClient#104]
Is this still for the V83 HeavenMS release? Some of the code files point to later versions of maple, and the packet structure is way off. Just trying to get in the loop, thanks.

**Comment by ryantpayton** [comment]
This would be for the v83 HeavenMS source code using latest GMS wz files.
Although I am using a custom version of HeavenMS located here:
https://github.com/ryantpayton/MapleStory
