### ISSUE TITLE
i want to your wzfile or nxfile

### ISSUE THREAD

**Issue by HoneyTorres** [HeavenClient/HeavenClient#105]
my file can not convert to nxfile by nolifewztonx,it always exception by bitmaps.
i dont know what reason. so i want to your nxfile.
cloud you upload anthor drive?

**Comment by ryantpayton** [comment]
I'll see if I can get you the latest this project is using.

**Comment by JunLiangW** [comment]
i also need that, please send me a copy, ths

**Comment by XiaoxingChen** [comment]
Me too, thank you!

**Comment by ryantpayton** [comment]
It looks like the latest version I was using was v228.3.
I converted these files and uploaded them to OneDrive. Here's the link:
https://1drv.ms/u/s!Al6eadQnem68lwqAivyS-6u28FW9?e=dhtc0U
@HoneyTorres @JunLiangW @XiaoxingChen

**Comment by h0353914** [comment]
link expired

**Comment by ryantpayton** [comment]
> link expired

I uploaded these 3 months ago. I cannot keep these up forever. A version close to this one will suffice.

**Comment by kevin375534653** [comment]
Could you upload it again, thank you！！！
