### ISSUE TITLE
Can I get a nx files for execute?

### ISSUE THREAD

**Issue by sangwoo98** [HeavenClient/HeavenClient#107]
Drive link is expired therefore can I get a nx files download link for execute?

**Comment by sangwoo98** [comment]
![image](https://user-images.githubusercontent.com/30223481/196051656-81c92f8e-b1a7-4b36-9c14-0cf015d40e10.png)
I execute succesfully but It seems like weird UI. I need nx files.

**Comment by manuelex20** [comment]
Same... How can I fix it? :(

**Comment by ryantpayton** [comment]
Please see issue #105
