### ISSUE TITLE
Movement issues from perspective of other players

### ISSUE THREAD

**Issue by lain3d** [HeavenClient/HeavenClient#65]
Video:
https://cdn.discordapp.com/attachments/570380824038342656/659677492889649154/bug_movement1.mov

"stuttering" when going up slanted platforms. down is fine.

**Comment by ryantpayton** [comment]
Is this the same client? Both HeavenClient?

**Comment by filoper** [comment]
When that happens this line is executed
https://github.com/HeavenClient/HeavenClient/blob/e85f7ac8d803e134a45bbd06f9f6583b95a88f1b/Gameplay/Physics/FootholdTree.cpp#L174
and the lines right after will set bad values
```
const Foothold &nextfh = get_fh(phobj.fhid);
phobj.fhslope = nextfh.slope(); // NaN because divide by 0

double ground = nextfh.ground_below(x); // NaN
```

The stuttering disappeared after I modified the else-block to
```
else {
    phobj.fhid = get_fhid_below(x, y);
    if (phobj.fhid == 0)
        return;
}
```
I have just begun looking at the code myself so don't know if this has any side effects, but hopefully it will help you implement a fix.

**Comment by ryantpayton** [comment]
Awesome! Will take a look and see if it fixes it for me and then I'll implement it unless you want to submit a PR for it.

**Comment by filoper** [comment]
You can implement it if you're happy with it. Cheers!
