### ISSUE TITLE
Upgrade to C++ 14 and beyond

### ISSUE THREAD

**Issue by leoxy520** [HeavenClient/HeavenClient#83]
Hi, first of all, so glad to see this active development of a custom client which I have been dreaming of ever since. I have dabbled in the early days of the original Journey Client, so it is great this is still being around!

I finally got this to compile locally, but I ran into issues when using VS2019 and C++ 14/17. It looks like the current code base does not support the latest C++? I had to add const to some const expr statements, change the non standard "for each in" loops, and add headers like <string>, <cmath> because for some reason the complier was complaining of "not a member of std". 

I am not sure if my changes are necessary, but that's just what I needed to do to compile this. So do you guys intend to upgrade to the latest C++? I am happy to contribute my changes. I am also interesting in contributing in general, which will be easier if we are using the same C++ standard.

**Comment by ryantpayton** [comment]
Hey @leoxy520,

Thanks for the suggestions and willing to help with the client! Anything would be very helpful and welcomed :)

As far as upgrading to the latest version, there are multiple devs using the same version and I think there is more needed than just changes to the files. I believe the libraries should be looked at as well. I believe some are pointing to an old build of VS to match what we are using.

I would suggest getting your environment to match with ours for the time being.
Configuration: Debug
Platform: x64
Target Platform Version: 8.1
Platform Toolset: Visual Studio 2015 (v140)
Configuration Type: Application (.exe)
Character Set: Use Unicode Character Set

Let me know if you need help or get any bugs. Also you can chat with us on discord: https://discordapp.com/channels/350831332609359875/421679367698120704/573980935423393794
