### ISSUE TITLE
Super duper noob question. (How do I spawn mobs?)

### ISSUE THREAD

**Issue by Souna** [HeavenClient/HeavenClient#86]
I'm using the `!spawn 100100` command to summon a regular snail. I'm also using the HeavenMS server.

After the command input my client doesn't show any spawned mob, and the maps don't spawn mobs by default. I am very new to this so any advice is appreciated. I will answer questions as needed.
Tysm 😁

**Comment by ryantpayton** [comment]
Sounds like a packet difference between your HeavenMS server and the Heaven Client.
I suggest using https://github.com/ryantpayton/MapleStory
