### ISSUE TITLE
client terminated unexpected after entering PIC at character selection stage

### ISSUE THREAD

**Issue by remifan** [HeavenClient/HeavenClient#87]
The HeavenMS server-side is deployed using its associated docker-compose file. The console output of HeavenMS can confrim user session `Log: players/createdchars/remi.txt remi created character with IGN xxxxx`, but the client immediately closed after entering PIC without throwing info. I cannot find out what happened under the hood.

This issue can be confirmed in the pre-compiled version and the master branch.

**Comment by JeffreyAngell** [comment]
I ran into this same issue. I was able to log in after changing to using the server mentioned [here](https://github.com/HeavenClient/HeavenClient/issues/93). The other server is a fork of HeavenMS, and doesn't have full compatibility if you've been running HeavenMS off a recent version for a while, but it's possible to merge in the changes from HeavenMS and get it to work (at least generally; I haven't done full testing yet).

I will soon be working on figuring out what patch is necessary on either HeavenMS or HeavenClient to get them to work together on more recent versions. I'm not sure how long it'll take me though.

**Comment by ryantpayton** [comment]
I don't plan on supporting newer versions of the HeavenMS server code. It's pretty much in a retired state and I have different goals in mind then how HeavenMS is being implemented. I would use the server code mentioned above, https://github.com/ryantpayton/MapleStory.
