### ISSUE TITLE
Compilation error when not using crypto

### ISSUE THREAD

**Issue by neeerp** [HeavenClient/HeavenClient#89]
When not defining USE_CRYPTO in maplestory.h, the project no longer compiles due to a couple of typos in cryptography.cpp:

* `HEADERLEN` is referenced when it should really be `HEADER_LENGTH`
* some name issues when casting in an #else with `length` and `slength`

**Comment by ryantpayton** [comment]
At this time I am not supporting Linux, but anyone else who has admin access to the repo can merge your PR if they want to. Thank you for your help and support. I will leave your PR untouched and ready to be committed.
