### ISSUE TITLE
Can’t enter any strings when I enter the login interface

### ISSUE THREAD

**Issue by 2mxd** [HeavenClient/HeavenClient#95]
Hello developer
After I generate the solution,in the game, I can’t enter any strings when I enter the login interface,Include letters and numbers, What should I do?
![ccc](https://user-images.githubusercontent.com/39205561/104980307-36946100-5a41-11eb-9360-0dca9f8473a6.PNG)

**Comment by JeffBusch** [comment]
If understand correctly you're probably missing the "fonts" folder in the directory with the exe. I forgot to copy it to my build directory and was missing all text.

**Comment by ryantpayton** [comment]
That's correct.
