### ISSUE TITLE
no WzLib.lib file

### ISSUE THREAD

**Issue by Thenck** [HeavenClient/HeavenClient#96]
the source code haven't WzLib.lib file  how to get it?

**Comment by ryantpayton** [comment]
You don't, you need to remove that reference from your project.

**Comment by Thenck** [comment]
thanks
but i only have *.wz file 
how to  make the  wz2nx? i find some tools but dosen't work

**Comment by ryantpayton** [comment]
I provide a tool for that. Please read the entire README file.
