### ISSUE TITLE
The magician's skill cannot change the mobCount??

### ISSUE THREAD

**Issue by xieyxpro** [HeavenClient/HeavenClient#97]
I change F/P Mage 's skill, whose id is 2101005.I add mobCount, lb and rt in skill.WZ. Also, I did same thing in Server's xml file.
Howevent, the skill can only attack one mob, I don't know why.Is it a bug?

**Comment by xieyxpro** [comment]
I see. This client is made by person, so something is not in this client.

**Comment by xieyxpro** [comment]
Will you continue to develop this project? @ryantpayton

**Comment by ryantpayton** [comment]
Yes, of course! :) @xieyxpro

**Comment by xieyxpro** [comment]
Sorry to bother you. I love GMS083，it is the best game and I want to change the game I played in my childhood. It seems like that the client doesn't have all the jobs(I mean the old five jobs and their sub jobs). For example，Magician has only F/P. I/L Mage is not in the client Now?
