### ISSUE TITLE
latest version can't connect to latest HeavenMS

### ISSUE THREAD

**Issue by kloklojul** [HeavenClient/HeavenClient#99]
compiling the latest version of the heavenClient produces a client that cannot connect to a freshly and unaltered server of heavenMS.
The server works just fine using a GMS client. But when trying to log in with the heavenclient you can enter your account details and choose a channel but as soon as you try to log into the channel the client throws this error :

`PacketSwitch::warn]: Opcode [CHARLIST] Error: Packet Error: Stack underflow at 189`

Also the client is than stuck in an endless loop.

**Comment by zstu-jack** [comment]
I have same error with you while geting character list.
have you solved the problem?
and do you have GMS client source code?

**Comment by zstu-jack** [comment]
when i try to use previous commit, the program normal quit when i choose one character before enter game(so i cannot get into game)
btw: the role does not show correctly.

**Comment by zgxmug** [comment]
same error

**Comment by Bear2leaf** [comment]
> I have same error with you while getting character list.
> have you solved the problem?
> and do you have GMS client source code?


I got same error earlier, then I resolved it by:

1. use ver **213** 's Wz, you can download from here [v213 (Direct Download) from ragezone](https://mega.nz/file/Xk823BzK#jScB5o2wxPc4jM02diZtZVy6MOjwgoJLA8_iU0nLfDo)
remember do not use the latest wz in gms client from nexon official website
**which may be the cause of your problem, at least for me** 
2. copy those wz files mentioned in NxFiles.h to path/to/NoLifeWzToNx.exe
3. open terminal and `cd path/to/NoLifeWzToNx.exe` 
4. use command `.\NoLifeWzToNx.exe -c .`
5. wait for parsing those wz files mentioned in NxFiles.h using NoLifeWzToNx

The details about wz version is already mentioned by ryan in README but I think it's still easy to be ignored, by the way there was a time I could not find ver **213** 's GMS full client. I found it and tried today and it worked!

let me know if you have any problems.

**Comment by ryantpayton** [comment]
> > I have same error with you while getting character list.
> > have you solved the problem?
> > and do you have GMS client source code?
> 
> I got same error earlier, then I resolved it by:
> 
> 1. use ver **213** 's Wz, you can download from here [v213 (Direct Download) from ragezone](https://mega.nz/file/Xk823BzK#jScB5o2wxPc4jM02diZtZVy6MOjwgoJLA8_iU0nLfDo)
>    remember do not use the latest wz in gms client from nexon official website
>    **which may be the cause of your problem, at least for me**
> 2. copy those wz files mentioned in NxFiles.h to path/to/NoLifeWzToNx.exe
> 3. open terminal and `cd path/to/NoLifeWzToNx.exe`
> 4. use command `.\NoLifeWzToNx.exe -c .`
> 5. wait for parsing those wz files mentioned in NxFiles.h using NoLifeWzToNx
> 
> The details about wz version is already mentioned by ryan in README but I think it's still easy to be ignored, by the way there was a time I could not find ver **213** 's GMS full client. I found it and tried today and it worked!
> 
> let me know if you have any problems.

Thank you for this. Yeah it's important to follow the steps I outline to the T. I got some changes I've been working on in the works. Hoping to get away from all custom Wz files and only use the latest GMS stuff.

**Comment by jxayly123** [comment]
> Yeah it's important to follow the steps I outline to the T. I got some changes I've been working on in the works. Hoping to get away from all custom Wz files and only use the latest GMS stuff.

but now the heavenclient needs v229.3 wz files and i've searched around ragezone. Sadly nothing found. Can help for providing    the wz files?
